# Generated by Django 3.1.2 on 2020-10-13 00:40

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_auto_20201013_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='side',
            name='colour',
            field=colorfield.fields.ColorField(default='#00FF00', max_length=18),
        ),
    ]
