# Generated by Django 3.1.2 on 2020-10-13 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0003_side_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='side',
            name='logo',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
