# Generated by Django 3.1.2 on 2020-10-13 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0004_side_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='side',
            name='logo',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
