# Generated by Django 3.1.2 on 2020-10-13 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0005_auto_20201013_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='side',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
