# Generated by Django 3.1.2 on 2020-10-13 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0006_side_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='side',
            name='logo',
            field=models.ImageField(blank=True, upload_to='upload'),
        ),
    ]
