# Generated by Django 3.1.2 on 2020-10-13 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0007_auto_20201013_0137'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='BannerConfigEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('value', models.CharField(default='0', max_length=100)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image.bannerconfig')),
            ],
        ),
    ]
