# Generated by Django 3.1.2 on 2020-10-13 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0012_auto_20201013_1613'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['-points', 'name']},
        ),
    ]
