# Generated by Django 3.1.2 on 2020-10-15 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0013_auto_20201013_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='side',
            name='points',
        ),
    ]
